import { test, expect } from '@playwright/test'

test('scope, clues, info, language and region drilldown', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('No observations yet.')).toBeVisible()
  const stopCard = page.locator('.clue-main').filter({ hasText: 'Red triangular sign with' })
  await page.getByRole('button', { name: /About this clue: Red triangular/ }).click()
  await expect(stopCard).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Close', exact: true }).first().click()
  await stopCard.click()
  await expect(stopCard).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /Japan .*%/ })).toBeVisible()
  const beforeLanguage = await page.locator('.chart-card').first().locator('[data-rank-id]').evaluateAll((nodes) => nodes.map((node) => [node.getAttribute('data-rank-id'), node.querySelector('.rank-value')?.textContent]))
  await page.getByText('简体中文', { exact: true }).click()
  await expect(page.getByText('国家匹配', { exact: true }).last()).toBeVisible()
  const afterLanguage = await page.locator('.chart-card').first().locator('[data-rank-id]').evaluateAll((nodes) => nodes.map((node) => [node.getAttribute('data-rank-id'), node.querySelector('.rank-value')?.textContent]))
  expect(afterLanguage).toEqual(beforeLanguage)
  await expect(page.getByRole('button', { name: /红色三角牌写有/ }).first()).toHaveAttribute('aria-pressed', 'true')
  await page.getByText('English', { exact: true }).click()
  await page.getByText('Custom countries').click()
  await page.getByLabel('United States', { exact: true }).check()
  await page.getByLabel('Canada', { exact: true }).check()
  await expect(page.getByText('2 candidates')).toBeVisible()
  await expect(page.getByRole('button', { name: /Japan .*%/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear clues' }).click()
  await expect(page.getByText('2 candidates')).toBeVisible()
  await page.getByLabel('Inspect a country').selectOption('CA')
  await expect(page.getByText('No reviewed regional rule is active')).toBeVisible()
  await page.getByRole('button', { name: 'A vehicle has a front plate', exact: true }).click()
  await expect(page.locator('.region-card .rank-row').filter({ hasText: 'Ontario' })).toBeVisible()
  await page.locator('.country-picker summary').click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.waitForTimeout(350)
  await page.screenshot({ path: 'test-results/desktop-1440-both.jpg', type: 'jpeg', quality: 55 })
})

test('a lower ranked country enters smoothly and reduced motion is honored', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Traffic keeps left', exact: true }).click()
  const before = await page.locator('[data-rank-id]').allTextContents()
  expect(before.some((text) => text.includes('Japan'))).toBe(false)
  await page.locator('.clue-main').filter({ hasText: 'Red triangular sign with' }).click()
  const japan = page.locator('[data-rank-id="JP"]')
  await expect(japan).toBeVisible()
  expect(await japan.evaluate((node) => node.getAnimations().length)).toBeGreaterThan(0)
  expect(await page.locator('.rank-list').first().locator('[data-rank-id]').last().getAttribute('data-rank-id')).toBe('__others__')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: 'Traffic keeps right', exact: true }).click()
  expect(await page.locator('.rank-list').first().locator('.rank-row').evaluateAll((nodes) => nodes.every((node) => node.getAnimations().length === 0))).toBe(true)
})

test('photo cards and local flags load at desktop width', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.goto('/')
  await page.locator('.clue-main').filter({ hasText: 'Red triangular sign with' }).click()
  await page.locator('.clue-main img').evaluateAll(async (nodes) => { await Promise.all(nodes.map(async (node) => { const image = node as HTMLImageElement; image.loading = 'eager'; await image.decode() })) })
  const images = await page.locator('img').evaluateAll((nodes) => nodes.map((node) => ({ src: (node as HTMLImageElement).src, ok: (node as HTMLImageElement).complete && (node as HTMLImageElement).naturalWidth > 0 })))
  expect(images.filter((image) => image.src.includes('/images/')).every((image) => image.ok)).toBe(true)
  expect(images.filter((image) => image.src.includes('/flags/')).every((image) => image.ok)).toBe(true)
  await page.waitForTimeout(350)
  await page.screenshot({ path: 'test-results/desktop-1920.jpg', type: 'jpeg', quality: 55 })
  await page.evaluate(() => window.scrollTo(0, 650))
  await page.screenshot({ path: 'test-results/desktop-1920-lower.jpg', type: 'jpeg', quality: 55 })
})







test('a viewed country closes when removed from scope, and a single-country panel can be closed', async ({ page }) => {
  await page.goto('/')
  await page.getByText('Custom countries').click()
  await page.getByLabel('Canada', { exact: true }).check()
  await expect(page.locator('.region-card')).toBeVisible()
  await page.locator('.region-card .close-region').click()
  await expect(page.locator('.region-card')).toHaveCount(0)
  await page.getByLabel('Inspect a country').selectOption('CA')
  await page.getByLabel('United States', { exact: true }).check()
  await page.getByLabel('Canada', { exact: true }).uncheck()
  await expect(page.locator('.region-card')).toHaveCount(0)
})
test('multiple photos of one clue remain a single selectable observation', async ({ page }) => {
  await page.goto('/')
  const card = page.locator('.clue-main').filter({ hasText: 'Yellow plate on the rear' })
  await page.getByRole('button', { name: 'About this clue: Yellow plate on the rear' }).click()
  await expect(page.getByRole('button', { name: 'Photo 2' })).toBeVisible()
  await page.getByRole('button', { name: 'Photo 2' }).click()
  await expect(page.locator('.modal-image img')).toHaveAttribute('src', /yellow-rear-plate\.jpg/)
  await expect(card).toHaveAttribute('aria-pressed', 'false')
})

test('Yuque source diagram is viewable in info without selecting the observation', async ({ page }) => {
  await page.goto('/')
  const clue = page.locator('.text-clue').filter({ hasText: 'Signpost painted black and yellow' })
  await clue.getByRole('button', { name: 'About this clue: Signpost painted black and yellow' }).click()
  await expect(clue.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'false')
  const diagram = page.locator('.source-figure img')
  await expect(diagram).toBeVisible()
  expect(await diagram.evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await expect(page.locator('.source-figure figcaption')).toContainText('historical context')
})
