import { test, expect } from '@playwright/test'

const clueSearch = (page: import('@playwright/test').Page) => page.getByRole('searchbox', { name: 'Search clue labels' })
const rows = (page: import('@playwright/test').Page, selector = '.chart-card') => page.locator(selector).first().locator('[data-rank-id]')

 test('local knowledge, info independence, language, hard scope and Brazil regions', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.getByText('Select any visual clue to compare countries.')).toBeVisible()
  await expect(page.locator('.gallery-count')).toContainText('324 illustrated')

  await page.locator('.inspect-select select').selectOption({ label: 'Brazil' })
  await expect(page.locator('.region-card h2')).toHaveText('Brazil')
  await expect(page.locator('.region-card .rank-row')).toHaveCount(6)
  const regionalIds = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-rank-id')))
  expect(regionalIds.at(-1)).toBe('__others__')
  const regionalValues = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(regionalValues.reduce((sum, value) => sum + value, 0)).toBe(100)

  await clueSearch(page).fill('ALTO')
  const alto = page.locator('.clue-card').filter({ hasText: 'The word ALTO' }).first()
  await expect(alto).toBeVisible()
  await alto.locator('.info-button').click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('The original source notes are in Chinese')
  await expect(page.locator('.info-details a').first()).toHaveAttribute('href', /yuque\.com/)
  await expect(alto.locator('.clue-main')).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await alto.locator('.clue-main').click()
  await expect(alto.locator('.clue-main')).toHaveAttribute('aria-pressed', 'true')
  const beforeLanguage = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => [node.getAttribute('data-rank-id'), node.querySelector('.rank-value')?.textContent]))
  await page.getByRole('button', { name: 'Switch to Simplified Chinese' }).click()
  await expect(page.locator('.region-card .chart-head')).toContainText('国内地区')
  const afterLanguage = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => [node.getAttribute('data-rank-id'), node.querySelector('.rank-value')?.textContent]))
  expect(afterLanguage).toEqual(beforeLanguage)
  await page.getByRole('button', { name: '清空线索' }).click()
  await expect(page.locator('.region-card h2')).toHaveText('巴西')
  await expect(page.getByText('尚未选择观察。候选初始权重相同，暂不显示最佳国家。')).toBeVisible()
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.waitForTimeout(400)
  await page.screenshot({ path: 'test-results/knowledge-brazil-1920.jpg', type: 'jpeg', quality: 55 })

  await page.locator('.language-switch').click()
  await page.locator('.country-picker summary').click()
  await page.getByLabel('Brazil', { exact: true }).check()
  await expect(page.getByText('1 candidates')).toBeVisible()
  await page.getByLabel('Argentina', { exact: true }).check()
  await page.getByLabel('Brazil', { exact: true }).uncheck()
  await expect(page.locator('.region-card')).toHaveCount(0)
})

test('free selection, explicit exclusion, certainty and mutually exclusive traffic-side observation', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('Traffic keeps left')
  const left = page.locator('.text-clue').filter({ hasText: 'Traffic keeps left' }).first()
  await expect(left).toBeVisible()
  await left.locator('.text-clue-pick').click()
  await expect(left.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'true')
  await clueSearch(page).fill('Traffic keeps right')
  const right = page.locator('.text-clue').filter({ hasText: 'Traffic keeps right' }).first()
  await right.locator('.text-clue-pick').click()
  await expect(right.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.selection-list .selection-chip')).toHaveCount(1)
  await expect(page.locator('.selection-list .selection-name')).toHaveText('Traffic keeps right')

  await clueSearch(page).fill('Yellow rear plate')
  const plate = page.locator('.clue-card').filter({ hasText: 'Yellow rear plate' }).first()
  await expect(plate).toBeVisible()
  await plate.locator('.card-exclude').click()
  await expect(page.locator('.selection-list .selection-mode').last()).toHaveText('Clearly absent')
  await plate.locator('.certainty-toggle').click()
  await expect(page.locator('.selection-list .selection-chip').last()).toContainText('Not sure')
  await page.getByRole('button', { name: 'Clear clues' }).click()
  await expect(page.locator('.selection-list .selection-chip')).toHaveCount(0)
  await expect(page.locator('.chart-empty')).toBeVisible()
})

test('scoped match rows remain normalized and Others stays last', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('ALTO')
  await page.locator('.clue-card .clue-main').first().click()
  const top = await rows(page, '.chart-card').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-rank-id')))
  expect(top.at(-1)).toBe('__others__')
  const values = await rows(page, '.chart-card').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(values.reduce((sum, value) => sum + value, 0)).toBe(100)
  await page.locator('.country-picker summary').click()
  await page.getByLabel('Brazil', { exact: true }).check()
  await page.getByLabel('Argentina', { exact: true }).check()
  await expect(page.getByText('2 candidates')).toBeVisible()
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]')).toHaveCount(3)
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]').last()).toHaveAttribute('data-rank-id', '__others__')
  await page.getByRole('button', { name: 'Clear clues' }).click()
  await expect(page.getByText('2 candidates')).toBeVisible()
})
test('all source photos are browsable by chapter without changing observations', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.gallery-count')).toContainText('324 illustrated')
  await page.getByRole('button', { name: 'Browse', exact: true }).click()
  await page.locator('.source-gallery-filter select').selectOption({ label: 'Brazil' })
  await expect(page.locator('.source-gallery .small-note').last()).toContainText('108 images')
  const firstImage = page.locator('.source-image-grid img').first()
  await expect(firstImage).toBeVisible()
  await expect.poll(async () => firstImage.evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await expect(page.locator('.selection-list .selection-chip')).toHaveCount(0)
})

test('compact screen keeps clue wording and separate info action usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.gallery-count')).toContainText('324 illustrated')
  await clueSearch(page).fill('ALTO')
  const card = page.locator('.clue-card').filter({ hasText: 'The word ALTO' }).first()
  await expect(card).toBeVisible()
  await card.locator('.info-button').click()
  await expect(card.locator('.clue-main')).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await expect.poll(async () => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/curated-mobile.jpg', type: 'jpeg', quality: 60, fullPage: true })
})


test('Canada and African source chapters open conditional regions with reviewed clue photos', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.locator('.gallery-count')).toContainText('324 illustrated')
  await page.locator('.inspect-select select').selectOption({ label: 'Canada' })
  await expect(page.locator('.region-card h2')).toHaveText('Canada')
  await expect(page.locator('.region-card [data-rank-id]')).toHaveCount(6)
  await clueSearch(page).fill('MAXIMUM')
  const maximum = page.locator('.clue-card').filter({ hasText: 'MAXIMUM on a speed sign' }).first()
  await expect(maximum).toBeVisible()
  const image = maximum.locator('.photo-wrap img').first()
  await expect.poll(async () => image.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
  await maximum.locator('.clue-main').click()
  const canadaRegionShares = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(canadaRegionShares.reduce((sum, value) => sum + value, 0)).toBe(100)
  await page.locator('.inspect-select select').selectOption({ label: 'South Africa' })
  await expect(page.locator('.region-card h2')).toHaveText('South Africa')
  await expect(page.locator('.region-card [data-rank-id]')).toHaveCount(6)
  await page.waitForTimeout(400)
  await page.screenshot({ path: 'test-results/canada-africa-1440.jpg', type: 'jpeg', quality: 65 })
})


test('manual geographic scope filters the gallery without discarding selected observations', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.gallery-count')).toContainText('324 illustrated')
  await page.getByRole('button', { name: 'Africa', exact: true }).click()
  await clueSearch(page).fill('Safaricom')
  const brand = page.locator('.clue-card').filter({ hasText: 'Safaricom shop sign or advert' })
  await expect(brand).toHaveCount(1)
  await brand.locator('.clue-main').click()
  await page.getByRole('button', { name: 'Global', exact: true }).click()
  await page.getByRole('button', { name: 'Europe', exact: true }).click()
  await expect(page.locator('.clue-card')).toHaveCount(0)
  await expect(page.locator('.selection-chip')).toHaveCount(1)
  await page.getByRole('button', { name: 'Global', exact: true }).click()
  await page.locator('.country-picker summary').click()
  await page.getByLabel('Canada', { exact: true }).check()
  await clueSearch(page).fill('Traffic keeps right')
  await expect(page.locator('.clue-card, .text-clue')).toHaveCount(0)
  await clueSearch(page).fill('Tamil text')
  await expect(page.locator('.clue-card, .text-clue')).toHaveCount(0)
  await clueSearch(page).fill('Yellow star on blue stripe')
  await expect(page.locator('.clue-card')).toHaveCount(1)
  await expect(page.locator('.selection-chip')).toHaveCount(1)
})

test('a photographed red chevron appears once and has no duplicate text clue', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('Single red chevron on broad white sign')
  await expect(page.locator('.clue-card')).toHaveCount(1)
  await expect(page.locator('.text-clue')).toHaveCount(0)
  const image = page.locator('.clue-card .photo-wrap img')
  await expect.poll(async () => image.evaluate((node: HTMLImageElement) => node.complete && node.naturalWidth > 0)).toBe(true)
})


test('an exact Acadian flag updates both charts without claiming one exclusive province', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.goto('/')
  await clueSearch(page).fill('Yellow star on blue stripe')
  const flag = page.locator('.clue-card').filter({ hasText: 'Yellow star on blue stripe of tricolor flag' })
  await expect(flag).toHaveCount(1)
  await flag.locator('.clue-main').click()
  await page.locator('.inspect-select select').selectOption({ label: 'Canada' })
  const country = rows(page, '.chart-card').first()
  await expect(country).toHaveAttribute('data-rank-id', 'loc:canada')
  expect(Number((await country.locator('.rank-value').innerText()).replace('%', ''))).toBeGreaterThan(90)
  const region = rows(page, '.region-card').first()
  await expect(region).toHaveAttribute('data-rank-id', 'loc:canada:region:ca-nb')
  const newBrunswick = Number((await region.locator('.rank-value').innerText()).replace('%', ''))
  expect(newBrunswick).toBeGreaterThan(50)
  expect(newBrunswick).toBeLessThan(90)
  await expect(page.locator('.region-card')).toContainText('Nova Scotia')
  await expect(page.locator('.region-card')).toContainText('Prince Edward Island')
})


test('continent and subregion presets combine as manual hard scopes', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Europe', exact: true }).click()
  const europeCount = Number((await page.locator('.scope-inline .count-pill').innerText()).trim())
  await page.getByRole('button', { name: 'Africa', exact: true }).click()
  const combinedCount = Number((await page.locator('.scope-inline .count-pill').innerText()).trim())
  expect(combinedCount).toBeGreaterThan(europeCount)
  await page.getByRole('button', { name: 'Europe', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Africa', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Global', exact: true }).click()
  await page.getByRole('button', { name: 'Southeast Asia', exact: true }).click()
  await expect(page.getByText('8 candidates')).toBeVisible()
  await page.getByRole('button', { name: 'East Asia', exact: true }).click()
  await expect(page.getByText('12 candidates')).toBeVisible()
  await page.getByRole('button', { name: 'Latin America', exact: true }).click()
  expect(Number((await page.locator('.scope-inline .count-pill').innerText()).trim())).toBeGreaterThan(12)
})


test('plate-color cards frame the corresponding plate in the shared source montage', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await clueSearch(page).fill('White vehicle plate')
  const white = page.locator('.clue-card').filter({ hasText: 'White vehicle plate' })
  await expect(white).toHaveCount(1)
  await expect(white.locator('.photo-wrap img')).toHaveClass(/crop-top/)
  await white.screenshot({ path: 'test-results/white-plate-card.jpg', type: 'jpeg', quality: 90 })
  await clueSearch(page).fill('Yellow vehicle plate')
  const yellow = page.locator('.clue-card').filter({ hasText: 'Yellow vehicle plate' })
  await expect(yellow).toHaveCount(1)
  await expect(yellow.locator('.photo-wrap img')).toHaveClass(/crop-bottom/)
  await yellow.screenshot({ path: 'test-results/yellow-plate-card.jpg', type: 'jpeg', quality: 90 })
})


test('green sign-back source says British Columbia is supported', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('Green back of a road sign')
  const card = page.locator('.clue-card').filter({ hasText: 'Green back of a road sign' })
  await expect(card).toHaveCount(1)
  await card.locator('.info-button').click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('source supports: British Columbia')
  await expect(dialog).toContainText('parent location inferred from regional source: Canada')
  await expect(dialog).not.toContainText('source opposes: British Columbia')
  await dialog.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'Switch to Simplified Chinese' }).click()
  await page.getByRole('searchbox').fill('路牌背面为绿色')
  await page.locator('.clue-card').filter({ hasText: '路牌背面为绿色' }).locator('.info-button').click()
  await expect(dialog).toContainText('原文支持：不列颠哥伦比亚省')
  await expect(dialog).toContainText('由地区原文推及上级地点：加拿大')
})


test('reviewed source contexts do not present contradictory geographic labels', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('Tamil text')
  const card = page.locator('.clue-card').filter({ hasText: 'Tamil text' })
  await expect(card).toHaveCount(1)
  await card.locator('.info-button').click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('source supports: India, Sri Lanka')
  await expect(dialog).not.toContainText('source opposes: Sri Lanka')
})
