import { test, expect } from '@playwright/test'

const clueSearch = (page: import('@playwright/test').Page) => page.getByRole('searchbox', { name: 'Search clue labels and source notes' })
const rows = (page: import('@playwright/test').Page, selector = '.chart-card') => page.locator(selector).first().locator('[data-rank-id]')

 test('local knowledge, info independence, language, hard scope and Brazil regions', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await expect(page.getByText('Select any visual clue to compare countries.')).toBeVisible()
  await expect(page.locator('.gallery-count')).toContainText('text-only')

  await page.locator('.inspect-select select').selectOption({ label: 'Brazil' })
  await expect(page.locator('.region-card h2')).toHaveText('Brazil')
  await expect(page.locator('.region-card .rank-row')).toHaveCount(6)
  const regionalIds = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-rank-id')))
  expect(regionalIds.at(-1)).toBe('__others__')
  const regionalValues = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(regionalValues.reduce((sum, value) => sum + value, 0)).toBe(100)

  await clueSearch(page).fill('ALTO')
  const alto = page.locator('.text-clue').filter({ hasText: 'ALTO' }).first()
  await expect(alto).toBeVisible()
  await alto.locator('.text-clue-info').click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('The original source notes are in Chinese')
  await expect(page.locator('.info-details a').first()).toHaveAttribute('href', /yuque\.com/)
  await expect(alto.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await alto.locator('.text-clue-pick').click()
  await expect(alto.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'true')
  const beforeLanguage = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => [node.getAttribute('data-rank-id'), node.querySelector('.rank-value')?.textContent]))
  await page.getByRole('button', { name: 'Switch to Simplified Chinese' }).click()
  await expect(page.locator('.region-card .chart-head')).toContainText('国内地区')
  const afterLanguage = await rows(page, '.region-card').evaluateAll((nodes) => nodes.map((node) => [node.getAttribute('data-rank-id'), node.querySelector('.rank-value')?.textContent]))
  expect(afterLanguage).toEqual(beforeLanguage)
  await page.getByRole('button', { name: '清空线索' }).click()
  await expect(page.locator('.region-card h2')).toHaveText('巴西')
  await expect(page.getByText('尚未选择观察。候选初始权重相同，暂不显示最佳国家。')).toBeVisible()
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.screenshot({ path: 'test-results/knowledge-brazil-1920.jpg', type: 'jpeg', quality: 55 })

  await page.locator('.language-switch').click()
  await page.locator('.country-picker summary').click()
  await page.getByLabel('Brazil', { exact: true }).check()
  await expect(page.getByText('1 candidates')).toBeVisible()
  await page.getByLabel('Argentina', { exact: true }).check()
  await page.getByLabel('Brazil', { exact: true }).uncheck()
  await expect(page.locator('.region-card')).toHaveCount(0)
})

test('free selection, explicit exclusion, certainty and mutually exclusive traffic-side observation', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('left-hand traffic')
  const left = page.locator('.text-clue').filter({ hasText: 'left-hand traffic' }).first()
  await expect(left).toBeVisible()
  await left.locator('.text-clue-pick').click()
  await expect(left.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'true')
  await clueSearch(page).fill('right-hand traffic')
  const right = page.locator('.text-clue').filter({ hasText: 'right-hand traffic' }).first()
  await right.locator('.text-clue-pick').click()
  await expect(right.locator('.text-clue-pick')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.selection-list .selection-chip')).toHaveCount(1)
  await expect(page.locator('.selection-list .selection-name')).toHaveText('right-hand traffic')

  await clueSearch(page).fill('yellow rear plate')
  const plate = page.locator('.clue-card').filter({ hasText: 'yellow rear plate' }).first()
  await expect(plate).toBeVisible()
  await plate.locator('.card-exclude').click()
  await expect(page.locator('.selection-list .selection-mode').last()).toHaveText('Clearly absent')
  await plate.locator('.certainty-toggle').click()
  await expect(page.locator('.selection-list .selection-chip').last()).toContainText('Not sure')
  await page.getByRole('button', { name: 'Clear clues' }).click()
  await expect(page.locator('.selection-list .selection-chip')).toHaveCount(0)
  await expect(page.locator('.chart-empty')).toBeVisible()
})

test('scoped match rows remain normalized and Others stays last', async ({ page }) => {
  await page.goto('/')
  await clueSearch(page).fill('ALTO')
  await page.locator('.text-clue-pick').first().click()
  const top = await rows(page, '.chart-card').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-rank-id')))
  expect(top.at(-1)).toBe('__others__')
  const values = await rows(page, '.chart-card').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(values.reduce((sum, value) => sum + value, 0)).toBe(100)
  await page.locator('.country-picker summary').click()
  await page.getByLabel('Brazil', { exact: true }).check()
  await page.getByLabel('Argentina', { exact: true }).check()
  await expect(page.getByText('2 candidates')).toBeVisible()
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]')).toHaveCount(3)
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]').last()).toHaveAttribute('data-rank-id', '__others__')
  await page.getByRole('button', { name: 'Clear clues' }).click()
  await expect(page.getByText('2 candidates')).toBeVisible()
})
