import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const openCustom = async (page: import('@playwright/test').Page) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Edit library' }).click()
  await expect(page.getByRole('heading', { name: 'My clue library' })).toBeVisible()
}

test('custom clue with uploaded image, Alberta weight, JSON export/import and local persistence', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await openCustom(page)
  await page.getByLabel('English clue label').fill('Black Street View car')
  await page.getByLabel('Chinese clue label').fill('黑色街景车')
  await page.locator('.custom-target-add select').first().selectOption({ label: 'Canada' })
  await page.locator('.custom-target-add select').nth(1).selectOption({ label: 'Alberta' })
  await page.getByRole('button', { name: 'Add location' }).click()
  const weight = page.locator('.custom-weight-row').first()
  await weight.getByLabel('When seen ×').fill('100')
  await weight.getByLabel('When clearly absent ×').fill('0.2')
  await page.locator('.custom-editor input[type="file"][accept^="image"]').setInputFiles('public/source-images/img-fd21ec1b26d5d45e.webp')
  await expect(page.locator('.custom-dropzone img')).toBeVisible()
  await page.getByRole('button', { name: 'Create clue' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Match clues' }).click()
  await page.getByRole('button', { name: 'My library' }).click()
  const card = page.locator('.clue-card').filter({ hasText: 'Black Street View car' })
  await expect(card).toBeVisible()
  await card.locator('.info-button').click()
  await expect(page.getByRole('dialog')).toContainText('Alberta: 100× / 0.2×')
  await expect(page.getByRole('dialog').locator('img')).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await card.locator('.clue-main').click()
  await expect(page.locator('.selection-chip')).toHaveCount(1)
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]').first()).toHaveAttribute('data-rank-id', 'loc:canada')
  await page.locator('.inspect-select select').selectOption({ label: 'Canada' })
  await expect(page.locator('.region-card [data-rank-id]').first()).toHaveAttribute('data-rank-id', 'loc:canada:region:ca-ab')
  const regionValues = await page.locator('.region-card [data-rank-id]').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(regionValues.reduce((sum, value) => sum + value, 0)).toBeCloseTo(100)
  await page.getByRole('button', { name: 'Global library' }).click()
  await expect(page.locator('.gallery-count')).toContainText('304 illustrated')
  await expect(page.locator('.selection-chip')).toHaveCount(0)
  await page.getByRole('button', { name: 'My library' }).click()
  await expect(page.locator('.selection-chip')).toHaveCount(1)
  await page.getByRole('button', { name: 'Edit library' }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON' }).click()
  const download = await downloadPromise
  const jsonBytes = await readFile(await download.path())
  const exported = JSON.parse(jsonBytes.toString())
  expect(exported.clues).toHaveLength(1)
  expect(exported.clues[0].imageDataUrl).toMatch(/^data:image\/webp;base64,/)
  expect(exported.clues[0].weights[0].locationId).toBe('loc:canada:region:ca-ab')
  await page.reload()
  await page.getByRole('button', { name: 'Edit library' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Delete: Black Street View car' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(0)
  await page.locator('.custom-editor input[type="file"][accept*="json"]').setInputFiles({ name: 'library.json', mimeType: 'application/json', buffer: jsonBytes })
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Switch to Simplified Chinese' }).click()
  await expect(page.getByRole('heading', { name: '我的线索题库' })).toBeVisible()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('黑色街景车')
  await page.screenshot({ path: 'test-results/custom-library-1440.jpg', type: 'jpeg', quality: 65 })
})

test('pasting an image into the custom image area works without a file picker', async ({ page }) => {
  await openCustom(page)
  await page.locator('.custom-dropzone').focus()
  await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 8; canvas.height = 8
    const context = canvas.getContext('2d')!; context.fillStyle = '#20252b'; context.fillRect(0, 0, 8, 8)
    const blob = await new Promise<Blob>((resolve) => canvas.toBlob((value) => resolve(value!), 'image/png'))
    const transfer = new DataTransfer(); transfer.items.add(new File([blob], 'pasted.png', { type: 'image/png' }))
    document.querySelector('.custom-dropzone')!.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
  })
  await expect(page.locator('.custom-dropzone img')).toBeVisible()
})


test('custom editor remains usable at a narrow viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openCustom(page)
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)
  expect(overflow).toBeLessThanOrEqual(2)
  await page.getByLabel('English clue label').fill('Black camera car')
  await page.locator('.custom-target-add select').first().selectOption({ label: 'Canada' })
  await page.locator('.custom-target-add select').nth(1).selectOption({ label: 'Alberta' })
  await page.getByRole('button', { name: 'Add location' }).click()
  await page.getByRole('button', { name: 'Create clue' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Match clues' }).click()
  await page.getByRole('button', { name: 'My library' }).click()
  await expect(page.locator('.text-clue').filter({ hasText: 'Black camera car' })).toBeVisible()
  await page.screenshot({ path: 'test-results/custom-library-mobile.jpg', type: 'jpeg', quality: 65 })
})


test('creates a second named library with isolated clues and observations', async ({ page }) => {
  await openCustom(page)
  await page.getByLabel('English clue label').fill('First library clue')
  await page.locator('.custom-target-add select').first().selectOption({ label: 'Canada' })
  await page.getByRole('button', { name: 'Add location' }).click()
  await page.getByRole('button', { name: 'Create clue' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)

  await page.getByRole('button', { name: 'New library' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(0)
  await page.getByLabel('Library name').fill('Africa practice')
  await page.getByRole('button', { name: 'Save name' }).click()
  await page.getByLabel('English clue label').fill('Second library clue')
  await page.locator('.custom-target-add select').first().selectOption({ label: 'Nigeria' })
  await page.getByRole('button', { name: 'Add location' }).click()
  await page.getByRole('button', { name: 'Create clue' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('Second library clue')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toContain('Africa-practice')
  const exported = JSON.parse((await readFile(await download.path())).toString())
  expect(exported.clues.map((clue: { appearance: { en: string } }) => clue.appearance.en)).toEqual(['Second library clue'])

  await page.getByRole('button', { name: 'Match clues' }).click()
  await page.getByRole('button', { name: 'My library' }).click()
  await expect(page.locator('.text-clue').filter({ hasText: 'Second library clue' })).toBeVisible()
  await page.locator('.text-clue').filter({ hasText: 'Second library clue' }).locator('.text-clue-pick').click()
  await expect(page.locator('.selection-chip')).toContainText('Second library clue')
  await page.getByLabel('Personal library').selectOption({ label: 'My library (1)' })
  await expect(page.locator('.text-clue').filter({ hasText: 'First library clue' })).toBeVisible()
  await expect(page.locator('.text-clue').filter({ hasText: 'Second library clue' })).toHaveCount(0)
  await expect(page.locator('.selection-chip')).toHaveCount(0)
  await page.locator('.text-clue').filter({ hasText: 'First library clue' }).locator('.text-clue-pick').click()
  await page.getByLabel('Personal library').selectOption({ label: 'Africa practice (1)' })
  await expect(page.locator('.selection-chip')).toContainText('Second library clue')

  await expect(page.locator('.custom-toolbar')).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit library' }).click()
  await expect(page.locator('.custom-toolbar')).toContainText('Saved in this browser')
  await page.reload()
  await page.getByRole('button', { name: 'Edit library' }).click()
  await expect(page.locator('.personal-library-manager select')).toHaveValue(/personal-/)
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('Second library clue')
  await page.locator('.personal-library-manager select').selectOption({ label: 'My library (1)' })
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('First library clue')
  await page.locator('.personal-library-manager select').selectOption({ label: 'Africa practice (1)' })
  await page.getByRole('button', { name: 'Delete library' }).click()
  await expect(page.locator('.personal-library-manager select option')).toHaveCount(2)
  await page.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(page.locator('.personal-library-manager select option')).toHaveCount(1)
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('First library clue')
})

test('migrates the previous IndexedDB single-library document', async ({ page }) => {
  await openCustom(page)
  const imageDataUrl = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII='
  await page.evaluate(async (imageDataUrl) => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('street-clues-custom-library', 1)
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    await new Promise<void>((resolve, reject) => {
      const transaction = db.transaction('documents', 'readwrite')
      transaction.objectStore('documents').put({ schemaVersion: 1, kind: 'street-clues-custom-library', clues: [{
        id: 'custom-legacy123', appearance: { en: 'Old pictured clue', zh: '旧图片线索' }, categoryId: 'camera', imageDataUrl,
        weights: [{ locationId: 'loc:canada', seenMultiplier: 5, absentMultiplier: 1 }],
      }] }, 'main')
      transaction.oncomplete = () => resolve()
      transaction.onerror = () => reject(transaction.error)
    })
    db.close()
  }, imageDataUrl)
  await page.reload()
  await page.getByRole('button', { name: 'Edit library' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('Old pictured clue')
  await expect(page.locator('.custom-clue-list .custom-list-item img')).toBeVisible()
  await page.getByRole('button', { name: 'New library' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(0)
  await page.locator('.personal-library-manager select').selectOption({ label: 'My library (1)' })
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('Old pictured clue')
})
