import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const openCustom = async (page: import('@playwright/test').Page) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'My library' }).click()
  await expect(page.getByRole('heading', { name: 'My clue library' })).toBeVisible()
}

test('custom clue with uploaded image, Alberta weight, JSON export/import and local persistence', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await openCustom(page)
  await page.getByLabel('English clue label').fill('Black Street View car')
  await page.getByLabel('Chinese clue label').fill('黑色街景车')
  await page.locator('.custom-target-add select').first().selectOption({ label: 'Canada' })
  await page.locator('.custom-target-add select').nth(1).selectOption({ label: 'Alberta' })
  await page.getByRole('button', { name: 'Add location' }).click()
  const weight = page.locator('.custom-weight-row').first()
  await weight.getByLabel('When seen ×').fill('100')
  await weight.getByLabel('When clearly absent ×').fill('0.2')
  await page.locator('.custom-editor input[type="file"][accept^="image"]').setInputFiles('public/source-images/img-fd21ec1b26d5d45e.webp')
  await expect(page.locator('.custom-dropzone img')).toBeVisible()
  await page.getByRole('button', { name: 'Create clue' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Hide editor' }).click()
  const card = page.locator('.clue-card').filter({ hasText: 'Black Street View car' })
  await expect(card).toBeVisible()
  await card.locator('.info-button').click()
  await expect(page.getByRole('dialog')).toContainText('Alberta: 100× / 0.2×')
  await expect(page.getByRole('dialog').locator('img')).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  await card.locator('.clue-main').click()
  await expect(page.locator('.selection-chip')).toHaveCount(1)
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]').first()).toHaveAttribute('data-rank-id', 'loc:canada')
  await page.locator('.inspect-select select').selectOption({ label: 'Canada' })
  await expect(page.locator('.region-card [data-rank-id]').first()).toHaveAttribute('data-rank-id', 'loc:canada:region:ca-ab')
  const regionValues = await page.locator('.region-card [data-rank-id]').evaluateAll((nodes) => nodes.map((node) => Number(node.querySelector('.rank-value')?.textContent?.replace('%', ''))))
  expect(regionValues.reduce((sum, value) => sum + value, 0)).toBeCloseTo(100)
  await page.getByRole('button', { name: 'Official library' }).click()
  await expect(page.locator('.gallery-count')).toContainText('304 illustrated')
  await expect(page.locator('.selection-chip')).toHaveCount(0)
  await page.getByRole('button', { name: 'My library' }).click()
  await expect(page.locator('.selection-chip')).toHaveCount(1)
  await page.getByRole('button', { name: 'Edit my library' }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON' }).click()
  const download = await downloadPromise
  const jsonBytes = await readFile(await download.path())
  const exported = JSON.parse(jsonBytes.toString())
  expect(exported.clues).toHaveLength(1)
  expect(exported.clues[0].imageDataUrl).toMatch(/^data:image\/webp;base64,/)
  expect(exported.clues[0].weights[0].locationId).toBe('loc:canada:region:ca-ab')
  await page.reload()
  await page.getByRole('button', { name: 'My library' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Delete: Black Street View car' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(0)
  await page.locator('.custom-editor input[type="file"][accept*="json"]').setInputFiles({ name: 'library.json', mimeType: 'application/json', buffer: jsonBytes })
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Switch to Simplified Chinese' }).click()
  await expect(page.getByRole('heading', { name: '我的线索题库' })).toBeVisible()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toContainText('黑色街景车')
  await page.screenshot({ path: 'test-results/custom-library-1440.jpg', type: 'jpeg', quality: 65 })
})

test('pasting an image into the custom image area works without a file picker', async ({ page }) => {
  await openCustom(page)
  await page.locator('.custom-dropzone').focus()
  await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 8; canvas.height = 8
    const context = canvas.getContext('2d')!; context.fillStyle = '#20252b'; context.fillRect(0, 0, 8, 8)
    const blob = await new Promise<Blob>((resolve) => canvas.toBlob((value) => resolve(value!), 'image/png'))
    const transfer = new DataTransfer(); transfer.items.add(new File([blob], 'pasted.png', { type: 'image/png' }))
    document.querySelector('.custom-dropzone')!.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
  })
  await expect(page.locator('.custom-dropzone img')).toBeVisible()
})


test('custom editor remains usable at a narrow viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openCustom(page)
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)
  expect(overflow).toBeLessThanOrEqual(2)
  await page.getByLabel('English clue label').fill('Black camera car')
  await page.locator('.custom-target-add select').first().selectOption({ label: 'Canada' })
  await page.locator('.custom-target-add select').nth(1).selectOption({ label: 'Alberta' })
  await page.getByRole('button', { name: 'Add location' }).click()
  await page.getByRole('button', { name: 'Create clue' }).click()
  await expect(page.locator('.custom-clue-list .custom-list-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Hide editor' }).click()
  await expect(page.locator('.text-clue').filter({ hasText: 'Black camera car' })).toBeVisible()
  await page.screenshot({ path: 'test-results/custom-library-mobile.jpg', type: 'jpeg', quality: 65 })
})
