import { expect, test } from '@playwright/test'

test('built-in Africa library is selectable and separate from the global and personal libraries', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Global library' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Africa library' }).click()
  await expect(page.locator('.library-picker-note').first()).toContainText('93 clues · 14 documented candidates')
  await expect(page.locator('.tree-all')).toContainText('93')
  await expect(page.locator('.scope-inline .count-pill')).toHaveText('14')
  const route = page.locator('.text-clue').filter({ hasText: 'Road number: R followed by digits' })
  await expect(route).toHaveCount(1)
  await route.locator('.text-clue-pick').click()
  await expect(page.locator('.chart-card').first().locator('[data-rank-id]').first()).toHaveAttribute('data-rank-id', 'loc:south-africa')
  await page.getByRole('button', { name: 'Global library' }).click()
  await expect(page.locator('.selection-chip')).toHaveCount(0)
  await expect(page.locator('.gallery-count')).toContainText('304 illustrated')
  await page.getByRole('button', { name: 'Africa library' }).click()
  await expect(page.locator('.selection-chip')).toHaveCount(1)
  await page.getByRole('button', { name: 'Edit library' }).click()
  await expect(page.getByRole('heading', { name: 'My clue library' })).toBeVisible()
  await expect(page.locator('.workspace')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Export JSON' }).locator('svg.lucide-upload')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Import JSON' }).locator('svg.lucide-download')).toHaveCount(1)
  await page.getByRole('button', { name: 'Match clues' }).click()
  await expect(page.locator('.selection-chip')).toHaveCount(1)
})
